# Generated by Django 5.2.4 on 2026-01-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='narration',
            field=models.TextField(blank=True),
        ),
    ]
