# Generated by Django 5.2.4 on 2025-12-27 05:46

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('gsm', 'GSM Modem'), ('mobile', 'Mobile as Modem'), ('api', 'Cloud API')], default='gsm', max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('usage_types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Document Expiry Reminder', 'Document Expiry Reminder'), ('Document Expired Reminder', 'Document Expired Reminder'), ('Invoice', 'Invoice'), ('Quotation', 'Quotation')], max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_config_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_config_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Configuration',
                'verbose_name_plural': 'SMS Configurations',
            },
        ),
        migrations.CreateModel(
            name='MobileModemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_port', models.CharField(default='', max_length=100)),
                ('mobile_baudrate', models.IntegerField(blank=True, default=9600, null=True)),
                ('mobile_timeout', models.IntegerField(blank=True, default=5, null=True)),
                ('sms_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_configs', to='sms_config.smsconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='GSMModemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsm_port', models.CharField(blank=True, max_length=50, null=True)),
                ('gsm_baudrate', models.PositiveIntegerField(blank=True, null=True)),
                ('gsm_timeout', models.PositiveIntegerField(blank=True, null=True)),
                ('sms_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gsm_configs', to='sms_config.smsconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_sender', models.CharField(blank=True, max_length=50, null=True)),
                ('sms_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_configs', to='sms_config.smsconfiguration')),
            ],
        ),
    ]
