# Generated by Django 5.2.4 on 2025-12-13 08:55

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsconfiguration',
            name='usage_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Document Expiry Reminder', 'Document Expiry Reminder'), ('Document Expired Reminder', 'Document Expired Reminder'), ('Invoice', 'Invoice'), ('Quotation', 'Quotation')], max_length=300),
        ),
    ]
