"""
Django settings for Lyraerp project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

from django.contrib.messages import constants as message_constants
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#3nbjk1zuz02@)^)#ukp5djq3=um9l71-0ycjri-!h*r_be6j='

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False 
DEBUG = True 
# ALLOWED_HOSTS = ['localhost', '127.0.0.1']
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
    'Project',
    'Employee',
    'UserReq',
    'Purchase',
    'widget_tweaks',
    'Tax',
    'user',
    'customer',
    'brand',
    'Items',
    'unit',
    'chart_of_accounts',
    'warehouse',
    'stock',
    'PayTerms',
    'sales',
    'HR',
    'department',
    'designation',
    'leaves',
    'bank',
    'allowances',
    'journal',
    'expenses',
    'mis_reports',
]
INSTALLED_APPS += ['django_countries']
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'Lyraerp.middleware.LoginRequiredMiddleware',
    'sales.middleware.SalesPermissionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Lyraerp.urls'
LOGIN_URL = '/login/'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'currencies.context_processors.company_base_currency_symbol',
                'django.contrib.auth.context_processors.auth',
                'HR.context_processors.hr_permissions',
                'sales.context_processors.sales_permissions',
                'django.contrib.messages.context_processors.messages',
                # user.permissions_for_request moved to end to override app flags
                'user.context_processors.permissions_for_request',
            ],
        },
    },
]

WSGI_APPLICATION = 'Lyraerp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'erp',
        'USER': 'root',
        'PASSWORD': 'Tiger#2024',
        'HOST': 'localhost',
        'PORT': '3307',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'   

# During development, add this so Django can serve static files itself
if DEBUG:
    STATICFILES_DIRS = [BASE_DIR / "static"] 

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]





# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = "kumardigamberjha@gmail.com"
EMAIL_HOST_PASSWORD = "zcfqvjoazsvfdsuz"
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

MESSAGE_TAGS = {
    message_constants.DEBUG: 'debug',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',  # Change error to danger here
}

AUTHENTICATION_BACKENDS = [
    'Lyraerp.auth_backend.CustomUserBackend',  # Your new backend
    'django.contrib.auth.backends.ModelBackend',  # Default backend (for superusers)
]

# File upload limits (allows up to 10 MB for file uploads)
# For 4 photos of 650 KB each = ~2.6 MB total, we need at least 5 MB + buffer
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB

# Default session lifespan: 2 weeks
SESSION_COOKIE_AGE = 1209600  # 14 days in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Do not expire on browser close by default
SESSION_SAVE_EVERY_REQUEST = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',  # Make sure INFO or DEBUG is set here
    },
}

# ========================================================
# LICENSE GENERATOR API CONFIGURATION
# ========================================================
# URL for the external license generator API
# Can be overridden with LICENSE_API_URL environment variable
LICENSE_GENERATOR_API_URL = os.getenv(
    'LICENSE_API_URL', 
    'http://license.myddns.me:8003'
)
# Whether to use an external API to infer country → currency mappings.
# Set to False in restricted environments or tests.
USE_COUNTRY_API = True
# For production with HTTPS: 'https://your-domain.com'
# For development: 'http://localhost:8002' or 'http://192.168.10.54:8002'
