# Generated by Django 5.2.4 on 2025-12-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_number',
            field=models.CharField(blank=True, help_text='Chart of Accounts reference number', max_length=50, null=True),
        ),
    ]
