# Generated by Django 5.2.4 on 2026-01-05 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_number',
        ),
    ]
