# Generated by Django 5.2.4 on 2026-01-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GstTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Gst Treatment',
                'db_table': 'gst_treatment',
            },
        ),
    ]
