# Generated by Django 5.2.4 on 2026-01-30 09:16

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayTerms', '0001_initial'),
        ('customer', '0005_gsttreatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='exemption_reason',
            field=models.TextField(blank=True, help_text='Reason for tax exemption (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gst_treatment',
            field=models.ForeignKey(blank=True, help_text='GST treatment applicable for this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customer.gsttreatment'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN (Permanent Account Number)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.ForeignKey(blank=True, help_text='Payment terms for this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='PayTerms.payterms'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address Line 1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address Line 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Shipping Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Shipping Postal Code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping State'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_preference',
            field=models.CharField(choices=[('taxable', 'Taxable'), ('tax_exempt', 'Tax Exempt')], default='taxable', help_text='Tax preference for this customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Billing Country'),
        ),
    ]
