# Generated by Django 5.2.4 on 2026-01-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_gsttreatments_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.CharField(default='INR', help_text='Currency code (e.g., INR, USD)', max_length=10),
        ),
    ]
