# Generated by Django 5.2.4 on 2026-05-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_customer_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
