# Generated by Django 5.2.4 on 2026-04-17 09:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Items', '0005_item_min_stock'),
        ('customer', '0009_alter_customer_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('rounding', models.CharField(choices=[('none', 'No Rounding'), ('nearest', 'Round to Nearest'), ('up', 'Round Up'), ('down', 'Round Down')], default='none', max_length=10)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'price_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_assignments', to='customer.customer')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_assignments', to='pricelist.pricelist')),
            ],
            options={
                'db_table': 'contact_price_lists',
                'unique_together': {('contact', 'price_list')},
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_method', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Price')], max_length=15)),
                ('adjustment_type', models.CharField(blank=True, choices=[('markup', 'Markup (Increase)'), ('markdown', 'Markdown (Decrease)')], max_length=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('custom_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_items', to='Items.item')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricelist.pricelist')),
            ],
            options={
                'db_table': 'price_list_items',
                'unique_together': {('price_list', 'item')},
            },
        ),
    ]
