# Generated by Django 5.2.4 on 2026-03-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('bank', '0002_bank_reconciliation'),
    ]

    operations = [
    ]
