# Generated by Django 5.2.4 on 2026-03-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_merge_0001_initial_0002_bank_reconciliation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankstatementline',
            new_name='bank_bankst_bank_ac_6b40c1_idx',
            old_name='bank_bankst_bank_ac_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatementline',
            new_name='bank_bankst_match_s_eea87b_idx',
            old_name='bank_bankst_match_s_idx',
        ),
    ]
