# Generated by Django 5.2.4 on 2026-03-26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_rename_bank_bankst_bank_ac_idx_bank_bankst_bank_ac_6b40c1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pattern', models.CharField(help_text='Regex or text fragment to match against statement description', max_length=255)),
                ('amount_tolerance', models.DecimalField(default=Decimal('0.00'), max_digits=12, decimal_places=2, help_text='Amount tolerance when matching (absolute difference)')),
                ('date_window', models.IntegerField(default=0, help_text='Number of days before/after statement date to search for transactions')),
                ('active', models.BooleanField(default=True)),
                ('auto_match', models.BooleanField(default=True, help_text='If true, apply this rule automatically')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(help_text='Bank account this rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='bank_rules', to='company_settings.companybankaccount')),
            ],
            options={
                'verbose_name': 'Bank Rule',
                'verbose_name_plural': 'Bank Rules',
            },
        ),
    ]
