# Generated by Django 5.2.4 on 2025-12-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_templates', '0002_add_template_name_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplateoption',
            name='style',
            field=models.CharField(default='Default', max_length=100),
        ),
        migrations.AlterField(
            model_name='smstemplateoption',
            name='template_name',
            field=models.CharField(choices=[('Document Expiry Reminder', 'Document Expiry Reminder'), ('Document Expired Reminder', 'Document Expired Reminder'), ('Invoice', 'Invoice'), ('Quotation', 'Quotation')], default='-', max_length=150),
        ),
    ]
