# Generated by Django 5.2.4 on 2026-05-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='fx_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='fx_rate_to_base',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='Exchange rate from expense currency to company base currency.', max_digits=18),
        ),
        migrations.AddField(
            model_name='expense',
            name='total_amount_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
