# Generated by Django 5.2.4 on 2025-11-15 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(blank=True, help_text='Unique warehouse code', max_length=50, null=True, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True, help_text='Warehouse physical address', null=True)),
                ('contact_phone', models.CharField(max_length=20, null=True)),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details', null=True)),
                ('warehouse_incharge', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['warehouse_name'],
            },
        ),
    ]
