# Generated by Django 5.2.4 on 2026-02-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_warehouse_only_one_default_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.TextField(help_text='Warehouse physical address', null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_incharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
