# Generated by Django 5.2.4 on 2026-04-18 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricelistitem',
            name='unique_pricelist_sku',
        ),
        migrations.AlterUniqueTogether(
            name='pricelistitem',
            unique_together={('price_list', 'item_sku')},
        ),
    ]
