# Generated by Django 5.2.4 on 2026-04-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0002_remove_pricelistitem_unique_pricelist_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='percentage_type',
            field=models.CharField(blank=True, choices=[('markup', 'Markup'), ('markdown', 'Markdown')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='percentage_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='pricing_scheme',
            field=models.CharField(choices=[('percentage', 'Markup or Markdown by a percentage'), ('individual', 'Enter the rate individually for each item')], default='individual', max_length=15),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='max_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
