# Generated by Django 5.2.4 on 2026-04-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0003_pricelist_percentage_type_pricelist_percentage_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='pricing_scheme',
            field=models.CharField(choices=[('percentage', 'Markup or Markdown by a percentage'), ('individual', 'Enter the rate individually for each item')], default='individual', help_text='Choose whether this applies a global percentage or individual line rates', max_length=20),
        ),
    ]
