# Generated by Django 5.2.4 on 2026-04-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0004_alter_pricelist_pricing_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='pricing_scheme',
            field=models.CharField(choices=[('percentage', 'All Items (Percentage)'), ('individual', 'Individual Items (Custom Rate)')], default='individual', help_text='Choose whether this applies a global percentage or individual line rates', max_length=20),
        ),
    ]
