# Generated by Django 5.2.4 on 2026-01-24 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='Account Holder Name', max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_swift_code', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='bank.bank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_bank_accounts', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_bank_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_bank_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bank__bank_name', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(help_text='License key from generator app', max_length=255, unique=True)),
                ('company_gst', models.CharField(blank=True, help_text='Company GST number from license', max_length=15, null=True)),
                ('company_pan', models.CharField(blank=True, help_text='PAN extracted from GST', max_length=10, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_users', models.IntegerField(default=10)),
                ('max_locations', models.IntegerField(blank=True, default=5, null=True)),
                ('module_access', models.JSONField(blank=True, default=dict, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('erp_version', models.CharField(default='1.0.0', help_text='ERP version this license is valid for (e.g., 1.0.0, 2.1.5)', max_length=20)),
                ('license_version', models.PositiveIntegerField(default=1, help_text='Internal license schema version')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activation_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='company.company')),
            ],
            options={
                'verbose_name': 'License Key',
                'verbose_name_plural': 'License Keys',
                'db_table': 'company_licensekey',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_updated', to=settings.AUTH_USER_MODEL)),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='company_settings.locationtype')),
            ],
        ),
    ]
