# Generated by Django 5.2.4 on 2026-02-02 05:10

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
