# Generated by Django 5.2.4 on 2026-02-06 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0002_alter_location_country'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='licensekey',
            table=None,
        ),
    ]
