# Generated by Django 5.2.4 on 2026-02-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0003_alter_licensekey_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='license_expired_email_last_sent',
            field=models.DateTimeField(blank=True, help_text="When the last 'license expired' email was sent", null=True),
        ),
    ]
