# Generated by Django 5.2.4 on 2026-02-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0005_licensekey_is_license_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='is_license_expired',
            field=models.BooleanField(default=False, help_text='Set to True at 12:00 AM on the DAY AFTER expiry_date. E.g., if expiry_date=2026-02-25, this becomes True on 2026-02-26 at 00:00. Used for all expiry checks (emails, activation, module access, etc.)'),
        ),
    ]
