# Generated by Django 5.2.4 on 2026-03-27 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0002_insert_default_acc1'),
        ('company_settings', '0006_alter_licensekey_is_license_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankaccount',
            name='chart_account',
            field=models.ForeignKey(blank=True, help_text='Ledger entry that tracks this bank account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_bank_accounts', to='chart_of_accounts.chartofaccounts'),
        ),
    ]
