# Generated by Django 5.2.4 on 2025-12-18 06:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_initial'),
        ('PayTerms', '0001_initial'),
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('bill_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('flat', 'Flat Amount')], default='flat', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PayTerms.payterms')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Purchase.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('prd_brcd', models.CharField(blank=True, max_length=100, null=True)),
                ('prd_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prd_taxgroup', models.CharField(blank=True, max_length=255, null=True)),
                ('prd_disvalue', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('prd_distype', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Purchase.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.item')),
            ],
        ),
    ]
