# Generated by Django 5.2.4 on 2025-12-18 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0002_bill_billitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='Purchase.purchaseorder'),
        ),
    ]
