# Generated by Django 5.2.4 on 2025-12-29 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0006_populate_payment_modes'),
        ('chart_of_accounts', '0002_insert_default_acc1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=15)),
                ('payment_number', models.CharField(help_text='Unique payment reference number', max_length=50, unique=True)),
                ('payment_date', models.DateField(help_text='Date of payment transaction')),
                ('payment_made_on', models.DateField(blank=True, help_text='Actual date when payment was made (if different)', null=True)),
                ('reference', models.CharField(blank=True, help_text='External reference number (check number, transaction ID, etc.)', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment', null=True)),
                ('send_email', models.BooleanField(default=False, help_text='Send payment notification email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Purchase.bill')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bill_payments', to=settings.AUTH_USER_MODEL)),
                ('paid_through', models.ForeignKey(help_text='Account from which payment was made', on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments', to='chart_of_accounts.chartofaccounts')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments', to='Purchase.paymentmode')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bill_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill Payment',
                'verbose_name_plural': 'Bill Payments',
                'db_table': 'bill_payment',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillPaymentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Payment related document', upload_to='bill_payments/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Purchase.billpayment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Attachment',
                'verbose_name_plural': 'Payment Attachments',
                'db_table': 'bill_payment_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['bill', 'payment_date'], name='bill_paymen_bill_id_c53a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['payment_number'], name='bill_paymen_payment_a22de3_idx'),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['payment_date'], name='bill_paymen_payment_acf0c2_idx'),
        ),
    ]
