# Generated by Django 5.2.4 on 2025-12-30 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0007_billpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='vendor',
            field=models.ForeignKey(default=1, help_text='Vendor receiving the payment', on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments', to='Purchase.vendor'),
            preserve_default=False,
        ),
    ]
