# Generated by Django 5.2.4 on 2025-12-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0008_billpayment_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpayment',
            name='payment_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
