# Generated by Django 5.2.4 on 2026-01-02 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0009_alter_billpayment_payment_number'),
        ('chart_of_accounts', '0002_insert_default_acc1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpayment',
            name='bill',
            field=models.ForeignKey(blank=True, help_text='Associated bill (null for advance payments)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Purchase.bill'),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['vendor', 'payment_date'], name='bill_paymen_vendor__cb389d_idx'),
        ),
    ]
