# Generated by Django 5.2.4 on 2026-01-02 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0010_alter_billpayment_bill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount allocated to this bill from the payment', max_digits=15)),
                ('payment_made_on', models.DateField(blank=True, help_text='Specific payment date for this bill (if different from main payment)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bill Payment Allocation',
                'verbose_name_plural': 'Bill Payment Allocations',
                'db_table': 'bill_payment_allocation',
                'ordering': ['bill__bill_number'],
            },
        ),
        migrations.RemoveIndex(
            model_name='billpayment',
            name='bill_paymen_bill_id_c53a1d_idx',
        ),
        migrations.RemoveField(
            model_name='billpayment',
            name='bill',
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total payment amount', max_digits=15),
        ),
        migrations.AddField(
            model_name='billpaymentallocation',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='Purchase.bill'),
        ),
        migrations.AddField(
            model_name='billpaymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_allocations', to='Purchase.billpayment'),
        ),
        migrations.AddIndex(
            model_name='billpaymentallocation',
            index=models.Index(fields=['payment', 'bill'], name='bill_paymen_payment_cd2a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='billpaymentallocation',
            index=models.Index(fields=['bill'], name='bill_paymen_bill_id_aaad0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billpaymentallocation',
            unique_together={('payment', 'bill')},
        ),
    ]
