# Generated by Django 5.2.4 on 2026-01-05 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0011_billpaymentallocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount: positive for credit (advance given), negative for debit (advance used)', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, help_text='Reference to the payment that created or used this advance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advance_transactions', to='Purchase.billpayment')),
                ('vendor', models.ForeignKey(help_text='Vendor for whom advance is maintained', on_delete=django.db.models.deletion.PROTECT, related_name='advance_payments', to='Purchase.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Advance Payment',
                'verbose_name_plural': 'Vendor Advance Payments',
                'db_table': 'vendor_advance_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor'], name='vendor_adva_vendor__de7158_idx'), models.Index(fields=['vendor', '-created_at'], name='vendor_adva_vendor__075b78_idx'), models.Index(fields=['payment'], name='vendor_adva_payment_aeb2ba_idx')],
            },
        ),
    ]
