# Generated by Django 5.2.4 on 2026-01-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0012_vendoradvancepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='order',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
