# Generated by Django 5.2.4 on 2026-01-06 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0013_bill_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='order_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='Purchase.purchaseorder'),
        ),
    ]
