# Generated by Django 5.2.4 on 2026-01-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0014_alter_bill_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='order',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
