# Generated by Django 5.2.4 on 2026-01-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0016_alter_bill_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='order',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
