# Generated by Django 5.2.4 on 2026-01-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0017_alter_bill_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpayment',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments', to='Purchase.paymentmode'),
        ),
    ]
