# Generated by Django 5.2.4 on 2026-01-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0018_alter_billpayment_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='order',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
