# Generated by Django 5.2.4 on 2026-01-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0019_alter_bill_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('not_paid', 'Not Paid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
