# Generated by Django 5.2.4 on 2026-01-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0021_bill_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstatus',
            name='code',
        ),
    ]
