# Generated by Django 5.2.4 on 2026-01-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0026_bill_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='shipping_address1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address Line 1'),
        ),
        migrations.AddField(
            model_name='bill',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address Line 2'),
        ),
        migrations.AddField(
            model_name='bill',
            name='shipping_attention',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Attention To'),
        ),
        migrations.AddField(
            model_name='bill',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping City'),
        ),
        migrations.AddField(
            model_name='bill',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping Country'),
        ),
        migrations.AddField(
            model_name='bill',
            name='shipping_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Shipping Email'),
        ),
        migrations.AddField(
            model_name='bill',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Shipping Phone'),
        ),
        migrations.AddField(
            model_name='bill',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Shipping Postal Code'),
        ),
        migrations.AddField(
            model_name='bill',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping State'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_address1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address Line 1'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address Line 2'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_attention',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Attention To'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping City'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping Country'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Shipping Email'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Shipping Phone'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Shipping Postal Code'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping State'),
        ),
    ]
