# Generated by Django 5.2.4 on 2026-01-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0027_bill_shipping_address1_bill_shipping_address2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True, verbose_name='Prefix')),
            ],
        ),
    ]
