# Generated by Django 5.2.4 on 2026-01-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0028_billprefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='place_of_supply',
            field=models.CharField(blank=True, help_text='Place of supply for the order', max_length=100, null=True, verbose_name='Place of Supply'),
        ),
    ]
