# Generated by Django 5.2.4 on 2026-01-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0029_purchaseorder_place_of_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='place_of_supply',
            field=models.CharField(blank=True, help_text='Place of supply for the bill', max_length=100, null=True, verbose_name='Place of Supply'),
        ),
    ]
