# Generated by Django 5.2.4 on 2026-01-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0030_add_bill_place_of_supply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='place_of_supply',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Place of Supply'),
        ),
    ]
