# Generated by Django 5.2.4 on 2026-01-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0031_remove_bill_place_of_supply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Place of Supply'),
        ),
    ]
