# Generated by Django 5.2.4 on 2026-01-23 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0032_bill_place_of_supply'),
        ('warehouse', '0003_warehouse_only_one_default_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse'),
        ),
    ]
