# Generated by Django 5.2.4 on 2026-02-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0035_vendor_currency_vendor_exemption_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('company', 'Company'), ('individual', 'Individual')], default='company', max_length=20),
        ),
    ]
