# Generated by Django 5.2.4 on 2026-02-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0036_alter_vendor_vendor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='currency',
            field=models.CharField(blank=True, default='INR', help_text='Currency code (e.g., INR, USD)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tax_preference',
            field=models.CharField(blank=True, choices=[('taxable', 'Taxable'), ('tax_exempt', 'Tax Exempt')], default='taxable', help_text='Tax preference for this customer', max_length=20, null=True),
        ),
    ]
