# Generated by Django 5.2.4 on 2026-02-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0037_alter_vendor_currency_alter_vendor_tax_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20),
        ),
    ]
