# Generated by Django 5.2.4 on 2026-02-21 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0038_alter_vendor_vendor_type'),
        ('warehouse', '0004_alter_warehouse_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse'),
            preserve_default=False,
        ),
    ]
