# Generated by Django 5.2.4 on 2026-02-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0039_deliverynote_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Billed', 'Billed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20),
        ),
    ]
