# Generated by Django 5.2.4 on 2026-02-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0040_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
