# Generated by Django 5.2.4 on 2026-03-10 08:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0041_alter_deliverynote_status'),
        ('warehouse', '0004_alter_warehouse_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(choices=[('delivery_note', 'Delivery Note'), ('delivery_note_reversal', 'Delivery Note Reversal'), ('purchase_return', 'Purchase Return'), ('sales_order', 'Sales Order'), ('adjustment', 'Manual Adjustment'), ('transfer', 'Warehouse Transfer')], max_length=50),
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('shipped_by', models.CharField(blank=True, max_length=255, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stock_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='Purchase.bill')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Purchase.vendor')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='Purchase.purchasereturn'),
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.billitem')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Purchase.purchasereturn')),
            ],
        ),
    ]
