# Generated by Django 5.2.4 on 2026-03-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0042_alter_stockmovement_reference_type_purchasereturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
