# Generated by Django 5.2.4 on 2026-04-30 06:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0046_purchaseorderitem_o_price'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='document_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_bill_currencies', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='bill',
            name='fx_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='fx_rate_to_base',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Exchange rate from bill currency to company base currency.', max_digits=18),
        ),
        migrations.AddField(
            model_name='bill',
            name='total_amount_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='billitem',
            name='o_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
