# Generated by Django 5.2.4 on 2026-03-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_phase3_employee_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='current_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('selected', 'Selected'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('offer_cancelled', 'Offer Cancelled'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('hold', 'Hold')], default='applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidatestatushistory',
            name='new_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('selected', 'Selected'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('offer_cancelled', 'Offer Cancelled'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('hold', 'Hold')], max_length=30),
        ),
    ]
