# Generated by Django 5.2.4 on 2026-04-07 04:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0020_alter_company_base_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 code, e.g. INR, USD', max_length=3)),
                ('symbol', models.CharField(blank=True, default='', max_length=8)),
                ('name', models.CharField(blank=True, default='', max_length=80)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('display_format', models.CharField(choices=[('1,234.56', '1,234.56'), ('1.234,56', '1.234,56'), ('1 234,56', '1 234,56')], default='1,234.56', max_length=20)),
                ('is_base', models.BooleanField(default=False, help_text='Organisation functional/base currency')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['company_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(db_index=True)),
                ('rate', models.DecimalField(decimal_places=10, help_text='Base currency amount for 1 unit of this foreign currency', max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))])),
                ('source', models.CharField(choices=[('feed', 'Exchange feed'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='currencies.currency')),
            ],
            options={
                'ordering': ['currency_id', '-effective_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_currency_company_code'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('currency', 'effective_from'), name='uniq_exchange_rate_currency_date'),
        ),
    ]
