# Generated by Django 5.2.4 on 2025-11-15 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tax', '0001_initial'),
        ('brand', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HSNCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='HSN Code, e.g. 0101', max_length=10, unique=True)),
                ('description', models.TextField(help_text='Description of the product associated with this HSN code')),
            ],
        ),
        migrations.CreateModel(
            name='SACCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='SAC Code, e.g. 0101', max_length=10, unique=True)),
                ('description', models.TextField(help_text='Description of the product associated with this SAC code')),
            ],
        ),
       
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Uom_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('goods', 'Goods'), ('service', 'Service')], default='goods', max_length=10)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_pref', models.CharField(choices=[('taxable', 'Taxable'), ('non_taxable', 'Non-Taxable')], default='taxable', max_length=20)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_account', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_desc', models.TextField(blank=True, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_account', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_desc', models.TextField(blank=True, null=True)),
                ('track_inventory', models.BooleanField(default=False)),
                ('taxincld_slprice', models.BooleanField(default=False)),
                ('taxincld_costprice', models.BooleanField(default=False)),
                ('inv_acc', models.CharField(blank=True, choices=[('inv_asset', 'Inventory Asset')], default='inv_asset', max_length=50, null=True, verbose_name='Inventory Account')),
                ('inv_method', models.CharField(blank=True, choices=[('FIFO', 'FIFO (First In First Out)'), ('WAC', 'WAC (Weighted Average Cost)')], default='FIFO', max_length=10, null=True, verbose_name='Inventory Valuation Method')),
                ('op_stock', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Opening Stock')),
                ('op_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Opening Stock Rate per Unit')),
                ('sac_code', models.IntegerField(blank=True, help_text='Store SAC Code ID from items_saccode table', null=True, verbose_name='SAC Code ID')),
                ('sales_info', models.BooleanField(default=False, verbose_name='Sales Information')),
                ('purchase_info', models.BooleanField(default=False, verbose_name='Purchase Information')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='brand.brand', verbose_name='Brand')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_created', to=settings.AUTH_USER_MODEL)),
                ('inter_tax_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tax.tax', verbose_name='Inter State Tax Rate')),
                ('intra_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tax.taxgroup', verbose_name='Intra State Tax Rate')),
                ('main_barcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_barcode_item', to='Items.barcode')),
            ],
        ),
    ]
