# Generated by Django 5.2.4 on 2026-03-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_item_category_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='min_stock',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For Load low stock prefferred vendor items', max_digits=15, null=True, verbose_name='Minimum Stock Level'),
        ),
    ]
