# Generated by Django 5.2.4 on 2026-09-09 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0007_item_sales_purchase_tax'),
        ('category', '0002_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='category.subcategory', verbose_name='Subcategory'),
        ),
    ]
