# Generated by Django 5.2.4 on 2025-11-15 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxname', models.CharField(max_length=255)),
                ('taxtype', models.CharField(choices=[('', 'Select a Tax Type'), ('CGST', 'CGST'), ('SGST', 'SGST'), ('IGST', 'IGST'), ('UTGST', 'UTGST'), ('Cess', 'Cess')], max_length=5)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crtd_at', models.DateTimeField(auto_now_add=True)),
                ('updt_at', models.DateTimeField(auto_now=True)),
                ('crtd_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxes_created', to=settings.AUTH_USER_MODEL)),
                ('updt_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxes_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('crtd_at', models.DateTimeField(auto_now_add=True)),
                ('updt_at', models.DateTimeField(auto_now=True)),
                ('crtd_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxgroups_created', to=settings.AUTH_USER_MODEL)),
                ('taxes', models.ManyToManyField(to='Tax.tax')),
                ('updt_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxgroups_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
