# Generated by Django 5.2.4 on 2026-03-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taxgroup',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
