# Generated by Django 5.2.4 on 2026-03-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0002_tax_status_taxgroup_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
