# Generated by Django 5.2.4 on 2026-03-28 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0003_taxtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_type',
            field=models.CharField(choices=[('single', 'Single'), ('split', 'Split'), ('group', 'Group')], default='single', max_length=10),
        ),
        migrations.AlterField(
            model_name='tax',
            name='taxtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tax.taxtype'),
        ),
        migrations.CreateModel(
            name='TaxComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='Tax.tax')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(blank=True, max_length=100, null=True)),
                ('to_state', models.CharField(blank=True, max_length=100, null=True)),
                ('rule_type', models.CharField(choices=[('intra', 'Intra State'), ('inter', 'Inter State')], max_length=10)),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='Tax.tax')),
            ],
        ),
    ]
