# Generated by Django 5.2.4 on 2026-05-16 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0004_tax_country_tax_name_tax_tax_type_alter_tax_taxtype_and_more'),
        ('company', '0021_add_exchange_rate_feeds_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxtype',
            name='country',
        ),
        migrations.AddField(
            model_name='tax',
            name='applicable_on',
            field=models.CharField(choices=[('Total Amount', 'Total Amount'), ('TAX', 'Tax')], default='BOTH', max_length=20),
        ),
        migrations.AddField(
            model_name='tax',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_scope',
            field=models.CharField(choices=[('BOTH', 'Both'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase')], default='ITEM', max_length=10),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_type',
            field=models.CharField(choices=[('GST', 'GST'), ('VAT', 'VAT'), ('SALES', 'Sales Tax'), ('TURNOVER', 'Turnover Tax'), ('NONE', 'None'), ('LOCAL', 'Local Tax')], default='GST', max_length=10),
        ),
        migrations.AlterField(
            model_name='tax',
            name='taxtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tax.taxtype'),
        ),
        migrations.CreateModel(
            name='TaxMaster',
            fields=[
                ('tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_name', models.CharField(max_length=255)),
                ('tax_type', models.CharField(choices=[('GST', 'GST'), ('VAT', 'VAT'), ('SALES', 'SALES'), ('TURNOVER', 'TURNOVER'), ('LOCAL', 'LOCAL')], max_length=20)),
                ('tax_scope', models.CharField(choices=[('ITEM', 'Item'), ('INVOICE', 'Invoice')], max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_method', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed')], max_length=10)),
                ('applicable_on', models.CharField(choices=[('ALL', 'All'), ('ITEM', 'Item'), ('CATEGORY', 'Category')], default='ALL', max_length=10)),
                ('tax_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_master_items', to='company.company')),
            ],
            options={
                'db_table': 'tax_master',
                'ordering': ['tax_order', 'tax_name'],
            },
        ),
    ]
