# Generated by Django 5.2.4 on 2026-05-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0006_add_tax_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxmaster',
            name='tax_type',
            field=models.CharField(choices=[('GST', 'GST'), ('VAT', 'VAT'), ('SALES', 'SALES/PURCHASE'), ('TURNOVER', 'TURNOVER'), ('LOCAL', 'LOCAL')], max_length=20),
        ),
    ]
