# Generated by Django 5.2.4 on 2026-05-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0007_alter_taxmaster_tax_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxmaster',
            name='tax_type',
            field=models.CharField(choices=[('GST', 'GST'), ('VAT', 'VAT'), ('SALES', 'SALES'), ('TURNOVER', 'TURNOVER'), ('LOCAL', 'LOCAL')], max_length=20),
        ),
    ]
