# Generated by Django 5.2.4 on 2026-05-25 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0006_convert_both_to_sales'),
        ('Tax', '0008_alter_taxmaster_tax_type'),
    ]

    operations = [
    ]
