# Generated by Django 5.2.4 on 2026-05-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0009_merge_20260525_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_scope',
            field=models.CharField(choices=[('SALES', 'Sales'), ('PURCHASE', 'Purchase')], default='SALES', max_length=10),
        ),
    ]
