# Generated by Django 5.2.4 on 2026-05-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0010_alter_tax_tax_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_scope',
            field=models.CharField(choices=[('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('BOTH', 'Both')], default='SALES', max_length=10),
        ),
    ]
