# Generated by Django 5.2.4 on 2026-06-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0011_alter_tax_tax_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxmaster',
            name='higher_tds_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxmaster',
            name='income_tax_act',
            field=models.CharField(blank=True, choices=[('new-2025', 'New Income Tax Act 2025'), ('old-1961', 'Income Tax Act 1961')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taxmaster',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxmaster',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxmaster',
            name='section',
            field=models.CharField(blank=True, choices=[('192', 'Section 192'), ('194c', 'Section 194C'), ('194j', 'Section 194J'), ('194q', 'Section 194Q')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='applicable_on',
            field=models.CharField(choices=[('Total Amount', 'Total Amount'), ('TAX', 'Tax')], default='Total Amount', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxmaster',
            name='tax_type',
            field=models.CharField(choices=[('GST', 'GST'), ('VAT', 'VAT'), ('SALES', 'SALES'), ('TURNOVER', 'TURNOVER'), ('LOCAL', 'LOCAL')], default='GST', max_length=20),
        ),
    ]
