# Generated by Django 5.2.4 on 2026-06-12 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0012_taxmaster_higher_tds_rate_taxmaster_income_tax_act_and_more'),
        ('company', '0025_alter_company_tax_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxmaster',
            name='higher_tds_rate',
        ),
        migrations.RemoveField(
            model_name='taxmaster',
            name='income_tax_act',
        ),
        migrations.RemoveField(
            model_name='taxmaster',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='taxmaster',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='taxmaster',
            name='section',
        ),
        migrations.CreateModel(
            name='TcsMaster',
            fields=[
                ('tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_name', models.CharField(max_length=255)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_tax_act', models.CharField(blank=True, choices=[('new-2025', 'New Income Tax Act 2025'), ('old-1961', 'Income Tax Act 1961')], max_length=50, null=True)),
                ('section', models.CharField(blank=True, choices=[('194c', 'Section 194C'), ('194j', 'Section 194J'), ('194q', 'Section 194Q'), ('192', 'Section 192')], max_length=50, null=True)),
                ('higher_rate', models.BooleanField(default=False)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcs_master_items', to='company.company')),
            ],
            options={
                'db_table': 'tcs_master',
                'ordering': ['tax_name'],
            },
        ),
        migrations.CreateModel(
            name='TdsMaster',
            fields=[
                ('tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_name', models.CharField(max_length=255)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_tax_act', models.CharField(blank=True, choices=[('new-2025', 'New Income Tax Act 2025'), ('old-1961', 'Income Tax Act 1961')], max_length=50, null=True)),
                ('section', models.CharField(blank=True, choices=[('194c', 'Section 194C'), ('194j', 'Section 194J'), ('194q', 'Section 194Q'), ('192', 'Section 192')], max_length=50, null=True)),
                ('higher_rate', models.BooleanField(default=False)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_master_items', to='company.company')),
            ],
            options={
                'db_table': 'tds_master',
                'ordering': ['tax_name'],
            },
        ),
    ]
