# Generated by Django 5.2.4 on 2026-06-22 06:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0013_remove_taxmaster_higher_tds_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcsmaster',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='tdsmaster',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
