# Generated by Django 5.2.4 on 2025-11-15 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this designation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation_created', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='department.department')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this designation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'designation',
                'verbose_name_plural': 'designations',
                'ordering': ['designation_name'],
            },
        ),
    ]
