# Generated by Django 5.2.4 on 2025-11-15 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('is_header', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('search_code', models.CharField(blank=True, help_text='Optional search code for quick lookup', max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this brand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='chart_of_accounts.chartofaccounts')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this brand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chart of Accounts',
                'db_table': 'chart_of_accounts',
            },
        ),
    ]
