# Generated by Django 5.2.4 on 2025-11-28 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('sales', '0006_alter_salesquotation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='lost_reason',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='opportunity',
        ),
        migrations.AlterField(
            model_name='followup',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='sales.salesquotation'),
        ),
        migrations.AlterField(
            model_name='update',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='sales.salesquotation'),
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
