# Generated by Django 5.2.4 on 2025-11-29 06:29

import django.db.models.deletion
from django.db import migrations, models


def cleanup_presales_interaction(apps, schema_editor):
    PreSalesInteraction = apps.get_model('crm', 'PreSalesInteraction')
    Employee = apps.get_model('HR', 'Employee')
    db = schema_editor.connection.alias
    
    # Get all valid employee IDs
    valid_emp_ids = set(Employee.objects.using(db).values_list('id', flat=True))
    
    # Clean up any assigned_employee ids that don't exist
    for pi in PreSalesInteraction.objects.using(db).exclude(assigned_employee__isnull=True):
        if pi.assigned_employee_id not in valid_emp_ids:
            pi.assigned_employee = None
            pi.save(update_fields=['assigned_employee'], using=db)


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_delete_employeeidproof'),
        ('crm', '0003_add_assigned_employee'),
    ]

    operations = [
        migrations.RunPython(
            code=cleanup_presales_interaction,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='presalesinteraction',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presales_employee', to='HR.employee'),
        ),
    ]
