# Generated by Codex on 2026-08-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_subcategory'),
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types', to='category.subcategory', verbose_name='Subcategory'),
        ),
    ]
