# Generated by Codex on 2026-08-01

import django.db.models.deletion
from django.db import migrations, models


def populate_type_subcategory(apps, schema_editor):
    Category = apps.get_model('category', 'Category')
    Subcategory = apps.get_model('category', 'Subcategory')
    Type = apps.get_model('type', 'Type')
    db_alias = schema_editor.connection.alias

    category, _ = Category.objects.using(db_alias).get_or_create(
        category_name='Uncategorized',
        defaults={'status': True},
    )
    subcategory, _ = Subcategory.objects.using(db_alias).get_or_create(
        category=category,
        subcategory_name='Uncategorized',
        defaults={'status': True},
    )
    Type.objects.using(db_alias).filter(subcategory__isnull=True).update(subcategory=subcategory)


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0002_type_subcategory'),
    ]

    operations = [
        migrations.RunPython(populate_type_subcategory, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='type',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='category.subcategory', verbose_name='Subcategory'),
        ),
    ]
