# Generated by Django 5.2.4 on 2026-02-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='date_format',
        ),
        migrations.RemoveField(
            model_name='company',
            name='language',
        ),
        migrations.RemoveField(
            model_name='company',
            name='timezone',
        ),
    ]
