# Generated by Django 5.2.4 on 2026-02-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_date_format_remove_company_language_and_more'),
        ('company', '0005_add_deferred_db_fields'),
    ]

    operations = [
    ]
