# Generated by Django 5.2.4 on 2026-02-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_merge_20260211_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='registration_code',
            new_name='company_code',
        ),
    ]
