# Generated by Django 5.2.4 on 2026-02-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_rename_registration_code_company_company_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(blank=True, help_text='Auto-generated code in format: COMPANYNAME-YEAR (e.g., TECHSOLUTIONS-2025)', max_length=30, null=True, unique=True),
        ),
    ]
