# Generated by Django 5.2.4 on 2026-02-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_options_alter_company_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='trial_active',
            field=models.BooleanField(default=True, help_text='Is the company currently in trial mode?'),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_created_at',
            field=models.DateTimeField(blank=True, help_text='When was the trial created (signup date)?', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_expired_email_last_sent',
            field=models.DateTimeField(blank=True, help_text='When was the last trial expired email sent?', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, help_text='When does the trial expire? (trial_started_at + 15 days)', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_reminder_sent',
            field=models.BooleanField(default=False, help_text='Has the 10-day reminder email been sent?'),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When was the trial reminder email sent?', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, help_text='When did the trial actually start (first login date)?', null=True),
        ),
    ]
