# Generated by Django 5.2.4 on 2026-02-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_trial_active_company_trial_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='trial_expired_email_last_sent',
            field=models.DateTimeField(blank=True, help_text='When was the last trial expired email sent? (sent every 3 days)', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='trial_reminder_sent',
            field=models.BooleanField(default=False, help_text='Has the day-10 reminder email been sent?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, help_text='When did the trial start? (same as signup date now)', null=True),
        ),
    ]
