# Generated by Django 5.2.4 on 2026-02-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_trial_expired_email_last_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_trial_expired',
            field=models.IntegerField(default=0, help_text='Flag: 1 = trial expired, 0 = trial active/not expired'),
        ),
    ]
