# Generated by Django 5.2.4 on 2026-02-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_add_is_trial_expired'),
    ]

    operations = [
    ]
