# Generated by Django 5.2.4 on 2026-02-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_remove_is_trial_expired_conflict'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='setup_checklist_shown',
            field=models.BooleanField(default=False, help_text='Has the post-setup checklist been shown to the user once?'),
        ),
    ]
