# Generated by Django 5.2.4 on 2026-02-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_company_setup_checklist_shown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
    ]
