# Generated by Django 5.2.4 on 2026-02-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_remove_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
