# Generated by Django 5.2.4 on 2026-02-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='show_logo_in_print_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
