# Generated by Django 5.2.4 on 2026-02-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_company_show_logo_in_print_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
