# Generated by Django 5.2.4 on 2026-03-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_company_global_credit_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='global_credit_limit',
            new_name='credit_limit',
        ),
    ]
