# Generated by Django 5.2.4 on 2026-04-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_rename_global_credit_limit_company_credit_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='base_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
