# Generated by Django 5.2.4 on 2026-05-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_add_exchange_rate_feeds_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_type',
            field=models.CharField(choices=[('GST', 'GST'), ('VAT', 'VAT'), ('SALES', 'SALES'), ('TURNOVER', 'TURNOVER'), ('NONE', 'NONE')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
