# Generated by Django 5.2.4 on 2026-05-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_company_tax_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_type',
            field=models.CharField(choices=[('GST', 'GST'), ('VAT', 'VAT'), ('SALES', 'SALES/PURCHASE'), ('TURNOVER', 'TURNOVER'), ('NONE', 'NONE')], max_length=20),
        ),
    ]
