# Generated by Django 5.2.4 on 2026-06-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_alter_company_tax_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_type',
            field=models.CharField(choices=[('GST', 'GST'), ('VAT', 'VAT'), ('SALES', 'SALES'), ('TURNOVER', 'TURNOVER'), ('NONE', 'NONE')], default='GST', max_length=20),
        ),
    ]
