# Generated by Django 5.2.4 on 2026-08-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_alter_company_tax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stock_management_on_delivery',
            field=models.BooleanField(default=True, help_text='When True: stock quantities are updated only when a Delivery is processed. When False: stock quantities are updated when payment is recorded for purchase/sales.'),
        ),
    ]
