# Generated by Assistant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_alter_company_tax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_load_cash_customer',
            field=models.BooleanField(
                default=False,
                help_text='Automatically select the Cash Customer when creating new sales quotations, orders, invoices, or performa invoices.'
            ),
        ),
    ]
