# Generated by Assistant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_add_auto_load_cash_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='show_base_transaction_summary',
            field=models.BooleanField(
                default=True,
                help_text='If enabled, show the base transaction summary block (div#base-transaction-summary) in relevant pages.'
            ),
        ),
    ]
