# Generated by Django 5.2.4 on 2026-08-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_company_stock_management_on_delivery'),
        ('company', '0027_add_show_base_transaction_summary'),
    ]

    operations = [
    ]
