# Generated by Django 5.2.4 on 2026-08-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_merge_20260810_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='print_paper_size',
            field=models.CharField(choices=[('A4', 'A4'), ('POS', 'POS / EPOS')], default='A4', help_text='Preferred paper size for printing documents.', max_length=20),
        ),
    ]
