# Generated by Django 5.2.4 on 2026-09-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_add_deletion_warning_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='deletion_warning_email_count',
            field=models.IntegerField(default=0, help_text='Number of deletion warning emails sent (0-3)'),
        ),
    ]
