"""
Django settings for Lyraerp project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from django.contrib.messages import constants as message_constants
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ensure logs directory exists so FileHandler can open log files
LOGS_DIR = BASE_DIR / 'logs'
try:
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
except Exception:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#3nbjk1zuz02@)^)#ukp5djq3=um9l71-0ycjri-!h*r_be6j='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # Set to False in production

# ALLOWED_HOSTS - required when DEBUG is False
ALLOWED_HOSTS = ["erp.techlyra.com",
    "www.erp.techlyra.com",]  # In production, specify your domain(s): ['yourdomain.com', 'www.yourdomain.com']

# Application definition

INSTALLED_APPS = [
    # ✅ FIXED: 'Lyraerp' removed — only the AppConfig path remains.
    # Both together caused: "Application labels aren't unique, duplicates: Lyraerp"
    'Lyraerp.apps.LyraerpConfig',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
    'masters',
    'Project',
    'Employee',
    'UserReq',
    'Purchase',
    'widget_tweaks',
    'Tax',
    'user',
    'customer',
    'brand',
    'Items',
    'category',
    'type',
    'unit',
    'chart_of_accounts',
    'warehouse',
    'stock',
    'PayTerms',
    'sales',
    'HR',
    'department',
    'designation',
    'leaves',
    'bank',
    'allowances',
    'journal',
    'expenses',
    'personaldocuments',
    'system_settings',
    'email_config',
    'sms_config',
    'crm',
    'sms_templates',
    'email_templates',
    'company',
    'currencies',
    'activity_log',
    'company_settings',
    # 'django_apscheduler',
    'pricelists',

]
INSTALLED_APPS += ['django_countries']
INSTALLED_APPS += ['cities_light']

# Keep the GeoNames cache inside the project and avoid MySQL text-index issues.
CITIES_LIGHT_DATA_DIR = str(BASE_DIR / 'cities_light_data')
CITIES_LIGHT_INDEX_SEARCH_NAMES = False
# ============================================================================
# MIDDLEWARE CONFIGURATION
# ============================================================================
MIDDLEWARE = [
    # ========================================
    # 1. CORE DJANGO MIDDLEWARE (MUST BE FIRST)
    # ========================================
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # ========================================
    # 2. SITE BLOCK
    # ========================================
    'Lyraerp.middleware.SiteBlockMiddleware',

    # ========================================
    # 3. REGISTRATION FLOW
    # ========================================
    'company.registration_middleware.RegistrationFlowMiddleware',
    'company.registration_middleware.RegistrationCompletionMiddleware',

    # ========================================
    # 4. COMPANY CODE EXTRACTION  (sets request.company_code)
    # ========================================
    'Lyraerp.middleware.CompanyCodeMiddleware',
    'Lyraerp.middleware.ViewKwargFilterMiddleware',

    # ========================================
    # 5. MIGRATION GUARD  ← MOVED HERE, right after company code is extracted
    #    Intercepts requests whose company DB is still being set up.
    #    Must be BEFORE CompanyDBMiddleware / LicenseMiddleware / any view code
    #    so that "Table doesn't exist" crashes never happen.
    # ========================================
    'Lyraerp.migration_guard_middleware.MigrationGuardMiddleware',

    # ========================================
    # 6. AUTO-FIX REDIRECTS
    # ========================================
    'Lyraerp.middleware.AutoCompanyCodeRedirectMiddleware',

    # ========================================
    # 7. COMPANY URL ENFORCER
    # ========================================
    'Lyraerp.middleware.CompanyURLEnforcerMiddleware',

    # ========================================
    # 8. LOGIN REQUIRED
    # ========================================
    'Lyraerp.middleware.LoginRequiredMiddleware',

    # ========================================
    # 8.5. SESSION TIMEOUT MANAGEMENT
    # ========================================
    'Lyraerp.middleware.SessionTimeoutMiddleware',

    # ========================================
    # 9. COMPANY DATABASE ROUTING
    # ========================================
    'Lyraerp.middleware.CompanyDBMiddleware',

    # ========================================
    # 10. LICENSE
    # ========================================
    'company.middleware.LicenseInfoMiddleware',
    'company.middleware.LicenseCheckMiddleware',

    # ========================================
    # 10.5. TRIAL EXPIRATION CHECK
    # ========================================
    'Lyraerp.middleware.TrialExpirationMiddleware',

    # ========================================
    # 11. MODULE PERMISSIONS
    # ========================================
    'Lyraerp.middleware.ModulePermissionMiddleware',

    # ========================================
    # 12. SALES PERMISSION
    # ========================================
    'sales.middleware.SalesPermissionMiddleware',

    # ========================================
    # 13. ACTIVITY LOGGING
    # ========================================
    'activity_log.middleware.ActivityLogMiddleware',

    # ========================================
    # 14. TEMPLATE FALLBACK (last)
    # ========================================
    'Lyraerp.middleware.TemplateFallbackMiddleware',

]

ROOT_URLCONF = 'Lyraerp.urls'
LOGIN_URL = '/login/'

# ============================================================================
# TEMPLATES CONFIGURATION
# ============================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'user.context_processors.permissions_for_request',
                'HR.context_processors.hr_permissions',
                'sales.context_processors.sales_permissions',
                'crm.context_processors.crm_permissions',
                'Lyraerp.context_processors.company_context',
                'django.contrib.messages.context_processors.messages',
                'company.context_processors.license_context',
                # Ensure unified user permission context runs last so it can
                # override per-app flags and enforce license filtering.

            ],
            # ============================================================================
            # CRITICAL: GLOBAL TEMPLATE TAGS
            # Makes company_url, company_path, and overridden {% url %} tag available
            # in ALL templates without needing {% load lyra_tags %}
            # ============================================================================
            'builtins': [
                'Lyraerp.templatetags.lyra_tags',
            ],
        },
    },
]

WSGI_APPLICATION = 'Lyraerp.wsgi.application'


# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================
# ============================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'lyramaster',
        'USER': 'lyrauser',
        'PASSWORD': 'TechL#2024',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Configure database routing for multi-tenant architecture
DATABASE_ROUTERS = ['Lyraerp.routers.CompanyDatabaseRouter']

# ============================================================================
# PASSWORD VALIDATION
# ============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================================================================
# INTERNATIONALIZATION
# ============================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ============================================================================
# STATIC FILES (CSS, JavaScript, Images)
# ============================================================================

STATIC_URL = '/static/'

# Static files directory (for development)
STATICFILES_DIRS = [
    BASE_DIR / "staticfiles",
]

# Static files collection directory (for production)
STATIC_ROOT = BASE_DIR / "staticfiles"

# ============================================================================
# MEDIA FILES (User uploads)
# ============================================================================

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================================================
# DEFAULT SETTINGS
# ============================================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Site-wide access block toggle. Set to True to block non-staff users from accessing the site
# and show a friendly "site blocked" page. Keep False by default.
SITE_BLOCK = False


# ============================================================================
# EMAIL CONFIGURATION (Django Default)
# ============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = "kumardigamberjha@gmail.com"
EMAIL_HOST_PASSWORD = "zcfqvjoazsvfdsuz"
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False


# ============================================================================
# MESSAGES FRAMEWORK
# ============================================================================
MESSAGE_TAGS = {
    message_constants.DEBUG: 'debug',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',  # Change error to danger here
}


# ============================================================================
# AUTHENTICATION BACKENDS
# ============================================================================
AUTHENTICATION_BACKENDS = [
    'Lyraerp.auth_backend.CustomUserBackend',  # Your new backend
    'django.contrib.auth.backends.ModelBackend',  # Default backend (for superusers)
]


# ============================================================================
# SESSION CONFIGURATION
# ============================================================================
# Default session lifespan: 2 weeks
SESSION_COOKIE_AGE = 1209600  # 14 days in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True


# ============================================================================
# LICENSE GENERATOR API
# ============================================================================
LICENSE_GENERATOR_API_URL = os.getenv('LICENSE_API_URL', 'http://puresam.ath.cx:8001')


# ============================================================================
# EMAIL CONFIGURATION (Application-specific)
# ============================================================================
# Base URL for generating login links in emails
# In production, set the BASE_URL environment variable (e.g. https://app.yourdomain.com)
BASE_URL = os.getenv('BASE_URL')
if not BASE_URL:
    if DEBUG:
        # Local development fallback
        BASE_URL = 'http://localhost:8000'
    else:
        # Fail fast in production when BASE_URL is not provided
        raise RuntimeError('BASE_URL environment variable must be set in production')

# Email backend configuration (overrides default above)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'techlyra.com'  # Or your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mailmaster@techlyra.com'  # Change to your email
EMAIL_HOST_PASSWORD = 'sree#5202NEHA'  # Use app-specific password for Gmail

# Email settings for registration
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_TIMEOUT = 10  # Seconds

# ============================================
# TESTING EMAIL (CONSOLE BACKEND)
# ============================================
# Uncomment this during development to print emails to console instead of sending them
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# ============================================================================
# DEFERRED DATABASE CREATION SETTINGS
# ============================================================================
# Allow first login to take longer for database creation
LOGIN_TIMEOUT = 300  # 5 minutes for first login database setup

# Background migration settings
ASYNC_MIGRATION_ENABLED = True
CRITICAL_APPS = ['user', 'company', 'company_settings']  # Apps that must migrate before login completes


# ============================================================================
# APSCHEDULER SETTINGS
# ============================================================================
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # seconds


# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================
#change info to debug for more verbose logging, especially for database creation steps
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'database_creation.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,  # <-- stops double print to root console
        },
        'Lyraerp.utils.db_utils': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,  # <-- stops double print to root console
        },
        'Lyraerp.utils.email_utils': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,  # <-- stops double print to root console
        },
        'website.views': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,  # <-- stops double print to root console
        },
        'Lyraerp.scheduler': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,  # <-- stops double print to root console
        },
        'Lyraerp.apps': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,  # <-- stops double print to root console
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# ============================================================================
# E-WAY BILL API CONFIGURATION - GSP (RECOMMENDED)
# ============================================================================
# NIC restricts direct API access to taxpayers generating 25,000+ invoices/month.
# Use a GSP (GST Suvidha Provider) for universal access. Most popular: Masters India

# ─────────────────────────────────────────────────────────────────────────────
# No GSP — using NIC direct sandbox
# SET TO True FOR TESTING (local mock, no internet needed)
# SET TO False TO USE REAL NIC SANDBOX WITH nictexxst/abcdef
# ─────────────────────────────────────────────────────────────────────────────
EWAY_BILL_MOCK = True       # ← Mock mode active for local testing

# No GSP — using NIC direct sandbox
EWAY_BILL_GSP = {}            # ← empty, router will skip GSP

# Fernet key for encrypting stored passwords
# ─────────────────────────────────────────────────────────────────────────────
# (Legacy) Direct NIC API - Only if you're shortlisted for 25,000+ invoices/month
# ─────────────────────────────────────────────────────────────────────────────
EWAY_BILL_API = {
    "BASE_URL": "https://gst.gov.in/bl/ewb",  # sandbox
    "SANDBOX": False,  # Set to False for production
}

# Fernet encryption key for E-Way Bill credentials storage (not needed for GSP, but kept for UI)
EWAY_BILL_ENCRYPT_KEY = "g2DAI33ozDfJ746sLtsYwdN2ZNrPFoK4vaN1hhiZ2jE="
