# Generated by Django 5.2.4 on 2025-11-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('item', models.CharField(max_length=35)),
                ('qty', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
    ]
