# Generated by Django 5.2.4 on 2025-11-15 06:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RightsDtl',
            fields=[
                ('rightdtl_id', models.AutoField(primary_key=True, serialize=False)),
                ('rightdtl_name', models.CharField(max_length=45)),
                ('rightdtl_acc', models.BooleanField()),
                ('rightdtl_inv', models.BooleanField()),
                ('rightdtl_pos', models.BooleanField()),
                ('rightdtl_pur', models.BooleanField()),
                ('rightdtl_hrm', models.BooleanField()),
                ('rightdtl_sys', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('crtd_at', models.DateTimeField(db_column='crtd_at', default=django.utils.timezone.now, verbose_name='Created At')),
                ('updt_at', models.DateTimeField(db_column='updt_at', default=django.utils.timezone.now, verbose_name='Updated At')),
                ('crtd_by', models.ForeignKey(blank=True, db_column='crtd_by', help_text='User who created this user role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userRole_created', to=settings.AUTH_USER_MODEL)),
                ('updt_by', models.ForeignKey(blank=True, db_column='updt_by', help_text='User who last updated this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userRole_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_name', models.CharField(max_length=45)),
                ('usr_pwd', models.CharField(max_length=128)),
                ('usr_fname', models.CharField(max_length=45)),
                ('usr_mail', models.CharField(max_length=45)),
                ('usr_phn', models.CharField(max_length=45)),
                ('usr_rmrks', models.CharField(blank=True, max_length=45, null=True)),
                ('crtd_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updt_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('crtd_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updt_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_users', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('usr_roleid', models.ForeignKey(db_column='usr_roleid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.role', verbose_name='User Role')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.module')),
                ('permission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.permissiontype')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.role')),
            ],
            options={
                'unique_together': {('role', 'module', 'permission_type')},
            },
        ),
    ]
