# Generated by Django 5.2.4 on 2026-01-15 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('company', '0005_licensekey_erp_version_licensekey_license_version'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='company.company', verbose_name='Company'),
        ),
    ]
