# Generated by Django 5.2.4 on 2026-02-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_role_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usr_fname',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
