# Generated by Django 5.2.4 on 2026-02-23 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_usr_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usr_phn',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits.', regex='^\\d+$')]),
        ),
    ]
