# Generated by Django 5.2.4 on 2026-02-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_usr_phn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usr_phn',
            field=models.CharField(max_length=15),
        ),
    ]
