# Generated by Django 5.2.4 on 2025-12-27 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(choices=[('Document Expiry Reminder', 'Document Expiry Reminder'), ('Document Expired Reminder', 'Document Expired Reminder'), ('Invoice', 'Invoice'), ('Quotation', 'Quotation')], default='-', max_length=150)),
                ('style', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_hardcoded', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['template_name', 'style'],
                'unique_together': {('template_name', 'style')},
            },
        ),
    ]
