# Generated by Django 5.2.4 on 2025-12-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0002_add_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplatestyle',
            name='template_name',
            field=models.CharField(choices=[('Document Expiry Reminder', 'Document Expiry Reminder'), ('Document Expired Reminder', 'Document Expired Reminder'), ('Invoice', 'Invoice'), ('Quotation', 'Quotation'), ('Order', 'Order')], default='-', max_length=150),
        ),
    ]
