# Generated by Django 5.2.4 on 2026-05-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0006_alter_emailtemplatestyle_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplatestyle',
            name='template_name',
            field=models.CharField(choices=[('Document Expiry Reminder', 'Document Expiry Reminder'), ('Document Expired Reminder', 'Document Expired Reminder'), ('Appointment Letter', 'Appointment Letter'), ('Invoice', 'Invoice'), ('Performa Invoice', 'Performa Invoice'), ('Quotation', 'Quotation'), ('Payment Received', 'Payment Received'), ('Payment Made', 'Payment Made'), ('Order', 'Order'), ('Bill', 'Bill')], default='-', max_length=150),
        ),
    ]
