# Generated by Django 5.2.4 on 2026-02-20 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial_period_locking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fiscalyear',
            new_name='system_sett_start_d_48ec65_idx',
            old_name='system_sett_start_d_idx',
        ),
        migrations.RenameIndex(
            model_name='fiscalyear',
            new_name='system_sett_is_lock_268a02_idx',
            old_name='system_sett_is_lock_idx',
        ),
    ]
