# Generated by Django 5.2.4 on 2026-03-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0003_backupschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='lock_bills',
            field=models.BooleanField(default=False, help_text='Lock bill transactions for this fiscal year'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='lock_expenses',
            field=models.BooleanField(default=False, help_text='Lock expense entries for this fiscal year'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='lock_invoices',
            field=models.BooleanField(default=False, help_text='Lock invoice transactions for this fiscal year'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='lock_items',
            field=models.BooleanField(default=False, help_text='Lock item master records for this fiscal year'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='lock_journals',
            field=models.BooleanField(default=False, help_text='Lock journal entries for this fiscal year'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='lock_payments',
            field=models.BooleanField(default=False, help_text='Lock payment transactions for this fiscal year'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='lock_stock',
            field=models.BooleanField(default=False, help_text='Lock stock transactions for this fiscal year'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='🔒 When TRUE: Prevents ALL edits (bills, items, journals, stock). View-only mode.'),
        ),
    ]
