# Generated by Django 5.2.4 on 2026-03-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0004_fiscalyear_lock_bills_fiscalyear_lock_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodlock',
            name='categories',
            field=models.CharField(blank=True, help_text='Comma-separated lock categories (items,stock,invoice,bill,payment,journal,expense,all)', max_length=200),
        ),
    ]
