# Generated by Django 5.2.4 on 2026-03-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0005_periodlock_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='lock_purchase_return',
            field=models.BooleanField(default=False, help_text='Lock purchase return transactions for this fiscal year'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='lock_sales_return',
            field=models.BooleanField(default=False, help_text='Lock sales return transactions for this fiscal year'),
        ),
    ]
