# Generated by Django 5.2.4 on 2026-04-13 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0006_fiscalyear_lock_purchase_return_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYearClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the closing process', max_length=20)),
                ('closing_journal_id', models.BigIntegerField(blank=True, help_text='ID of the closing journal entry created during year-end', null=True)),
                ('opening_journal_id', models.BigIntegerField(blank=True, help_text='ID of the opening balances journal entry for next FY', null=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, help_text='Total income for the fiscal year', max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, help_text='Total expenses for the fiscal year', max_digits=15)),
                ('net_profit_loss', models.DecimalField(decimal_places=2, default=0, help_text='Net profit (if positive) or loss (if negative)', max_digits=15)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When was the closing completed?', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about the closing process')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_closings_completed', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.OneToOneField(help_text='The fiscal year being closed', on_delete=django.db.models.deletion.CASCADE, related_name='closing_record', to='system_settings.fiscalyear')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_closings_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiscal Year Closing',
                'verbose_name_plural': 'Fiscal Year Closings',
                'db_table': 'system_settings_fiscalyearclosing',
            },
        ),
    ]
