# Generated by Django 5.2.4 on 2026-04-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0007_fiscalyearclosing'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='lock_purchase_delivery',
            field=models.BooleanField(default=False, help_text='Lock purchase delivery note transactions for this fiscal year'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='lock_sales_delivery',
            field=models.BooleanField(default=False, help_text='Lock sales delivery note transactions for this fiscal year'),
        ),
    ]
