# Generated by Django 5.2.4 on 2025-12-29 11:29

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_config', '0002_add_usage_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='usage_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Document Expiry Reminder', 'Document Expiry Reminder'), ('Document Expired Reminder', 'Document Expired Reminder'), ('Invoice', 'Invoice'), ('Quotation', 'Quotation'), ('Order', 'Order')], max_length=300),
        ),
    ]
