# Generated by Django 5.2.4 on 2026-03-03 08:23

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_config', '0004_alter_emailconfiguration_usage_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='usage_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Document Expiry Reminder', 'Document Expiry Reminder'), ('Document Expired Reminder', 'Document Expired Reminder'), ('Invoice', 'Invoice'), ('Quotation', 'Quotation'), ('Payment Received', 'Payment Received'), ('Payment Made', 'Payment Made'), ('Order', 'Order'), ('Bill', 'Bill')], max_length=300),
        ),
    ]
