# Generated by Django 5.2.4 on 2025-11-17 04:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Items', '0002_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True, verbose_name='Prefix')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True, verbose_name='Prefix')),
            ],
        ),
        migrations.CreateModel(
            name='QuotePrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True, verbose_name='Prefix')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('flat', 'Flat Amount')], default='flat', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesperson')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_brcd', models.CharField(blank=True, max_length=100, null=True)),
                ('prd_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prd_taxgroup', models.CharField(blank=True, max_length=255, null=True)),
                ('prd_disvalue', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('prd_distype', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.item')),
                ('sales_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('flat', 'Flat Amount')], default='flat', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesperson')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_brcd', models.CharField(blank=True, max_length=100, null=True)),
                ('prd_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prd_taxgroup', models.CharField(blank=True, max_length=255, null=True)),
                ('prd_disvalue', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('prd_distype', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.item')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=20, unique=True, verbose_name='Quote#')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount Value')),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('flat', 'Flat Amount')], default='flat', max_length=10, verbose_name='Discount Type')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('SENT', 'Sent to Supplier')], default='DRAFT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesperson')),
            ],
        ),
        migrations.CreateModel(
            name='SalesQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_brcd', models.CharField(blank=True, max_length=100, null=True)),
                ('prd_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prd_taxgroup', models.CharField(blank=True, max_length=255, null=True)),
                ('prd_disvalue', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('prd_distype', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('Sales_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesquotation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.item')),
            ],
        ),
    ]
