# Generated by Django 5.2.4 on 2025-11-20 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayTerms', '0001_initial'),
        ('sales', '0002_salesquotation_payment_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PayTerms.payterms'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PayTerms.payterms'),
        ),
    ]
