# Generated by Django 5.2.4 on 2025-11-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesinvoice_payment_term_salesorder_payment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesquotationitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
