# Generated by Django 5.2.4 on 2025-11-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_created_from_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Viewed', 'Viewed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Draft', max_length=20),
        ),
    ]
