# Generated by Django 5.2.4 on 2025-12-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_salesquotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquotation',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Place of Supply'),
        ),
    ]
