# Generated by Django 5.2.4 on 2025-12-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salesquotation_shipping_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Place of Supply'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_address1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address Line 1'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address Line 2'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_attention',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Attention To'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping City'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping Country'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Shipping Email'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Shipping Phone'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Shipping Postal Code'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping State'),
        ),
    ]
