# Generated by Django 5.2.4 on 2025-12-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesinvoice_place_of_supply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesquotation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Draft', max_length=20),
        ),
    ]
