# Generated by Django 5.2.4 on 2025-12-19 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_salesorder_status_alter_salesquotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='origin_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesquotation'),
        ),
    ]
