# Generated by Django 5.2.4 on 2025-12-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_salesinvoice_origin_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Invoiced', 'Invoiced')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesquotation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Invoiced', 'Invoiced')], default='Draft', max_length=20),
        ),
    ]
