# Generated by Django 5.2.4 on 2026-01-05 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0005_paymentmode_alter_bill_status'),
        ('chart_of_accounts', '0002_insert_default_acc1'),
        ('customer', '0004_remove_customer_account_number'),
        ('sales', '0013_alter_salesorder_status_alter_salesquotation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total payment amount', max_digits=15)),
                ('payment_number', models.PositiveIntegerField(unique=True)),
                ('payment_date', models.DateField(help_text='Date of payment transaction')),
                ('payment_made_on', models.DateField(blank=True, help_text='Actual date when payment was made (if different)', null=True)),
                ('reference', models.CharField(blank=True, help_text='External reference number (check number, transaction ID, etc.)', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment', null=True)),
                ('send_email', models.BooleanField(default=False, help_text='Send payment notification email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inv_payments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer receiving the payment', on_delete=django.db.models.deletion.PROTECT, related_name='inv_payments', to='customer.customer')),
                ('paid_through', models.ForeignKey(help_text='Account from which payment was made', on_delete=django.db.models.deletion.PROTECT, related_name='inv_payments', to='chart_of_accounts.chartofaccounts')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inv_payments', to='Purchase.paymentmode')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inv_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inv Payment',
                'verbose_name_plural': 'Inv Payments',
                'db_table': 'inv_payment',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount allocated to this inv from the payment', max_digits=15)),
                ('payment_made_on', models.DateField(blank=True, help_text='Specific payment date for this inv (if different from main payment)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='sales.salesinvoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_allocations', to='sales.invpayment')),
            ],
            options={
                'verbose_name': 'Inv Payment Allocation',
                'verbose_name_plural': 'Inv Payment Allocations',
                'db_table': 'inv_payment_allocation',
                'ordering': ['inv__inv_number'],
            },
        ),
        migrations.CreateModel(
            name='InvPaymentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Payment related document', upload_to='inv_payments/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sales.invpayment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Attachment',
                'verbose_name_plural': 'Payment Attachments',
                'db_table': 'inv_payment_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invpayment',
            index=models.Index(fields=['customer', 'payment_date'], name='inv_payment_custome_62f0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='invpayment',
            index=models.Index(fields=['payment_number'], name='inv_payment_payment_8fe472_idx'),
        ),
        migrations.AddIndex(
            model_name='invpayment',
            index=models.Index(fields=['payment_date'], name='inv_payment_payment_aa5828_idx'),
        ),
        migrations.AddIndex(
            model_name='invpaymentallocation',
            index=models.Index(fields=['payment', 'inv'], name='inv_payment_payment_c03727_idx'),
        ),
        migrations.AddIndex(
            model_name='invpaymentallocation',
            index=models.Index(fields=['inv'], name='inv_payment_inv_id_280ea6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invpaymentallocation',
            unique_together={('payment', 'inv')},
        ),
    ]
