# Generated by Django 5.2.4 on 2026-01-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_salesinvoice_place_of_supply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Place of Supply'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Place of Supply'),
        ),
        migrations.AlterField(
            model_name='salesquotation',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Place of Supply'),
        ),
    ]
