# Generated by Django 5.2.4 on 2026-01-17 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_account_number'),
        ('sales', '0016_alter_salesinvoice_place_of_supply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount: positive for credit (advance received), negative for debit (advance used)', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(help_text='Customer for whom advance is maintained', on_delete=django.db.models.deletion.PROTECT, related_name='advance_payments', to='customer.customer')),
                ('payment', models.ForeignKey(blank=True, help_text='Reference to the payment that created or used this advance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advance_transactions', to='sales.invpayment')),
            ],
            options={
                'verbose_name': 'Customer Advance Payment',
                'verbose_name_plural': 'Customer Advance Payments',
                'db_table': 'customer_advance_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='customer_ad_custome_e417d0_idx'), models.Index(fields=['customer', '-created_at'], name='customer_ad_custome_01d2c1_idx'), models.Index(fields=['payment'], name='customer_ad_payment_a66315_idx')],
            },
        ),
    ]
