# Generated by Django 5.2.4 on 2026-02-02 11:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_customeradvancepayment'),
        ('stock', '0001_initial'),
        ('warehouse', '0003_warehouse_only_one_default_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note_number', models.CharField(max_length=20, unique=True)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('shipped_by', models.CharField(blank=True, help_text='Name of person who shipped', max_length=100, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('stock_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='sales.salesinvoice')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Sales Delivery Note',
                'verbose_name_plural': 'Sales Delivery Notes',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_type', models.CharField(choices=[('sales_delivery_note', 'Sales Delivery Note'), ('sales_delivery_note_reversal', 'Sales Delivery Note Reversal')], max_length=50)),
                ('reference_id', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.salesdeliverynote')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_movements', to='stock.stock')),
            ],
            options={
                'verbose_name': 'Sales Stock Movement',
                'verbose_name_plural': 'Sales Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesDeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delivered', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesdeliverynote')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesinvoiceitem')),
            ],
            options={
                'unique_together': {('delivery_note', 'invoice_item')},
            },
        ),
    ]
