# Generated by Django 5.2.4 on 2026-02-03 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0036_alter_vendor_vendor_type'),
        ('sales', '0018_salesdeliverynote_salesstockmovement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invpayment',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inv_payments', to='Purchase.paymentmode'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Invoiced', 'Invoiced')], default='Draft', max_length=20),
        ),
    ]
