# Generated by Django 5.2.4 on 2026-02-03 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0036_alter_vendor_vendor_type'),
        ('sales', '0019_alter_invpayment_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='Purchase.paymentstatus'),
        ),
    ]
