# Generated by Django 5.2.4 on 2026-02-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_salesinvoice_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
