# Generated by Django 5.2.4 on 2026-02-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_alter_salesinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='salesdeliverynote',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
