# Generated by Django 5.2.4 on 2026-03-04 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_customer_currency_and_more'),
        ('sales', '0022_salesperson_phone_alter_salesdeliverynote_status'),
        ('warehouse', '0004_alter_warehouse_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesstockmovement',
            name='reference_type',
            field=models.CharField(choices=[('sales_delivery_note', 'Sales Delivery Note'), ('sales_delivery_note_reversal', 'Sales Delivery Note Reversal'), ('sales_return', 'Sales Return'), ('sales_return_reversal', 'Sales Return Reversal')], max_length=50),
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('shipped_by', models.CharField(blank=True, max_length=255, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_type', models.CharField(choices=[('refund', 'Refund'), ('credit', 'Credit')], default='credit', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stock_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.salesinvoice')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='salesstockmovement',
            name='sales_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.salesreturn'),
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesinvoiceitem')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesreturn')),
            ],
        ),
    ]
