# Generated by Django 5.2.4 on 2026-03-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_alter_salesstockmovement_reference_type_salesreturn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturn',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Returned'), ('cancelled', 'Cancelled')], default='received', max_length=20),
        ),
    ]
