# Generated by Django 5.2.4 on 2026-03-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_alter_salesreturn_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturn',
            name='refund_type',
        ),
    ]
