# Generated by Django 5.2.4 on 2026-03-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_remove_salesreturn_refund_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
