# Generated by Django 5.2.4 on 2026-03-20 07:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0005_item_min_stock'),
        ('PayTerms', '0001_initial'),
        ('customer', '0009_alter_customer_currency_and_more'),
        ('sales', '0026_salesreturn_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformaInvoicePrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True, verbose_name='Prefix')),
            ],
        ),
        migrations.CreateModel(
            name='PerformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('flat', 'Flat Amount')], default='flat', max_length=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('place_of_supply', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place of Supply')),
                ('shipping_attention', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Attention To')),
                ('shipping_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Shipping Email')),
                ('shipping_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Shipping Phone')),
                ('shipping_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping Country')),
                ('shipping_address1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address Line 1')),
                ('shipping_address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address Line 2')),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping City')),
                ('shipping_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping State')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Shipping Postal Code')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PayTerms.payterms')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesperson')),
            ],
        ),
        migrations.CreateModel(
            name='PerformaInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('prd_brcd', models.CharField(blank=True, max_length=100, null=True)),
                ('prd_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prd_taxgroup', models.CharField(blank=True, max_length=255, null=True)),
                ('prd_disvalue', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('prd_distype', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('performa_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.performainvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.item')),
            ],
        ),
    ]
