# Generated by Django 5.2.4 on 2026-03-21 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_performainvoiceprefix_performainvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='origin_performa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='sales.performainvoice'),
        ),
    ]
