# Generated by Django 5.2.4 on 2026-03-31 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_invoicetax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicetax',
            options={'ordering': ['invoice_id', 'id'], 'verbose_name': 'Invoice Tax', 'verbose_name_plural': 'Invoice Taxes'},
        ),
        migrations.AddField(
            model_name='invoicetax',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicetax',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicetax',
            name='tax_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicetax',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
