# Generated by Django on 2026-03-31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_alter_invoicetax_options_invoicetax_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
            preserve_default=False,
        ),
    ]
