# Generated by Django 5.2.4 on 2026-03-31 09:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_salesinvoiceitem_tax_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoiceitem',
            name='tax_amount',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
