# Generated by Django 5.2.4 on 2026-04-04 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0043_purchasereturn_updated_at'),
        ('sales', '0032_remove_salesinvoiceitem_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Purchase.paymentstatus'),
        ),
    ]
