# Generated by Django 5.2.4 on 2026-04-07 07:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('sales', '0034_salesinvoice_fx_rate_to_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='document_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='fx_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='total_amount_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
    ]
