# Generated by Django 5.2.4 on 2026-04-13 10:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('sales', '0035_salesinvoice_document_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquotation',
            name='document_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quotations', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='fx_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='fx_rate_to_base',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Exchange rate from quotation currency to company base currency.', max_digits=18),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='total_amount_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
    ]
