# Generated by Django 5.2.4 on 2026-04-14 10:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_salesquotation_document_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='prd_disvalue',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='prd_disvalue',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='salesquotationitem',
            name='prd_disvalue',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
    ]
