# Generated by Django 5.2.4 on 2026-04-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_salesorder_document_currency_salesorder_fx_rate_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='document_currency',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='fx_rate_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='fx_rate_to_base',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='total_amount_base',
        ),
    ]
