# Generated by Django 5.2.4 on 2026-04-20 04:48

import django.db.models.deletion
import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_add_exchange_rate_feeds_enabled'),
        ('sales', '0040_salesorder_document_currency_salesorder_fx_rate_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ewb_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='E-Way Bill Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to NIC'), ('generated', 'Generated'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('gstin_from', models.CharField(blank=True, max_length=15, verbose_name='GSTIN (Supplier)')),
                ('gstin_to', models.CharField(blank=True, max_length=15, verbose_name='GSTIN (Recipient)')),
                ('place_from', models.CharField(blank=True, max_length=100, verbose_name='From City')),
                ('place_to', models.CharField(blank=True, max_length=100, verbose_name='To City')),
                ('pincode_from', models.CharField(blank=True, max_length=6, verbose_name='From Pincode')),
                ('pincode_to', models.CharField(blank=True, max_length=6, verbose_name='To Pincode')),
                ('state_from', models.CharField(blank=True, max_length=50, verbose_name='From State')),
                ('state_to', models.CharField(blank=True, max_length=50, verbose_name='To State')),
                ('mode_of_transport', models.CharField(choices=[('1', 'Road'), ('2', 'Rail'), ('3', 'Air'), ('4', 'Ship')], default='1', max_length=1)),
                ('vehicle_number', models.CharField(blank=True, max_length=15, verbose_name='Vehicle Number')),
                ('vehicle_type', models.CharField(choices=[('R', 'Regular'), ('O', 'ODC (Over Dimensional Cargo)')], default='R', max_length=1)),
                ('transporter_id', models.CharField(blank=True, max_length=15, verbose_name='Transporter ID')),
                ('transporter_name', models.CharField(blank=True, max_length=100)),
                ('transport_doc_no', models.CharField(blank=True, max_length=30, verbose_name='Transport Doc No.')),
                ('transport_doc_date', models.DateField(blank=True, null=True, verbose_name='Transport Doc Date')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hsn_code', models.CharField(blank=True, max_length=8, verbose_name='Primary HSN Code')),
                ('approximate_distance', models.IntegerField(default=0, verbose_name='Approx. Distance (km)')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_upto', models.DateTimeField(blank=True, help_text='Expiry date/time returned by NIC API', null=True, verbose_name='Valid Upto')),
                ('alert', models.TextField(blank=True, help_text='Warnings or notes from NIC API response', verbose_name='API Alert/Warning')),
                ('api_raw_response', models.JSONField(blank=True, help_text='Full JSON response from NIC stored for audit trail', null=True, verbose_name='Raw API Response')),
                ('cancel_reason_code', models.CharField(blank=True, choices=[('1', 'Duplicate'), ('2', 'Order Cancelled'), ('3', 'Data Entry Mistake'), ('4', 'Others')], max_length=2, verbose_name='Cancel Reason Code')),
                ('cancel_remarks', models.CharField(blank=True, help_text='Reason provided when cancelling', max_length=200, verbose_name='Cancel Remarks')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eway_bill', to='sales.salesinvoice')),
            ],
            options={
                'verbose_name': 'E-Way Bill',
                'verbose_name_plural': 'E-Way Bills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EWayBillCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=15, verbose_name='GSTIN')),
                ('username', models.CharField(max_length=100, verbose_name='NIC Portal Username')),
                ('_password', models.CharField(blank=True, db_column='password', default='', max_length=500, verbose_name='Password (encrypted)')),
                ('app_key', models.CharField(default=sales.models._default_app_key, help_text='Auto-generated. Do not share.', max_length=32, verbose_name='App Key (32-char AES session key)')),
                ('nic_public_key', models.TextField(blank=True, help_text='Paste the RSA public key from https://ewaybillgst.gov.in/apidoc/ here.', verbose_name='NIC Public Key (PEM)')),
                ('is_sandbox', models.BooleanField(default=False, help_text='Enable for testing; disable for production.', verbose_name='Use Sandbox (testing)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ewb_credential', to='company.company')),
            ],
            options={
                'verbose_name': 'E-Way Bill Credential',
                'verbose_name_plural': 'E-Way Bill Credentials',
            },
        ),
    ]
