# Generated by Django 5.2.4 on 2026-04-21 05:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_performainvoice_document_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performainvoiceitem',
            name='prd_disvalue',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
    ]
