# Generated by Django 5.2.4 on 2026-04-21 05:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0043_alter_performainvoiceitem_prd_disvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='performainvoiceitem',
            name='o_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
