# Generated by Django 5.2.4 on 2026-05-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_salesinvoice_turnover_tax'),
        ('sales', '0046_increase_sales_line_rate_precision'),
    ]

    operations = [
    ]
