# Generated by Django 5.2.4 on 2026-05-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0008_alter_taxmaster_tax_type'),
        ('sales', '0047_merge_20260520_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='performainvoice',
            name='turnover_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performa_invoices_turnover_tax', to='Tax.tax'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='turnover_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_turnover_tax', to='Tax.tax'),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='turnover_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quotations_turnover_tax', to='Tax.tax'),
        ),
    ]
