# Generated by Django 5.2.4 on 2026-06-24 07:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_performainvoice_turnover_tax_salesorder_turnover_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquotation',
            name='tds_tcs_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='TDS/TCS Amount'),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='tds_tcs_definition_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TDS/TCS Definition ID'),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='tds_tcs_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='TDS/TCS Rate'),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='tds_tcs_type',
            field=models.CharField(blank=True, choices=[('tds', 'TDS'), ('tcs', 'TCS')], default='tds', max_length=10, null=True, verbose_name='TDS/TCS Type'),
        ),
    ]
