# Generated by Django 5.2.4 on 2026-08-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0050_performainvoice_tds_tcs_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesstockmovement',
            name='reference_type',
            field=models.CharField(choices=[('sales_delivery_note', 'Sales Delivery Note'), ('sales_delivery_note_reversal', 'Sales Delivery Note Reversal'), ('sales_return', 'Sales Return'), ('sales_return_reversal', 'Sales Return Reversal'), ('sales_invoice_payment', 'Sales Invoice Payment')], max_length=50),
        ),
    ]
