# Generated by Django 5.2.4 on 2026-09-04 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0051_alter_stockmovement_reference_type'),
        ('sales', '0051_alter_salesstockmovement_reference_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='payment_status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='Purchase.paymentstatus'),
        ),
    ]
